covscanhub: load JSON with utf-8 encoding in add_title_to_json()
... to avoid traceback on RHEL-8 when running in POSIX locale:
```
Scan failed due to: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/covscanhub/scan/xmlrpc_helper.py", line 35, in finish_scan
    process_scan(sb)
  File "/usr/lib/python3.6/site-packages/covscanhub/waiving/results_loader.py", line 216, in process_scan
    rp.generate_diffs()
  File "/usr/lib/python3.6/site-packages/covscanhub/waiving/results_loader.py", line 84, in generate_diffs
    return self.rp.generate_diffs()
  File "/usr/lib/python3.6/site-packages/covscanhub/waiving/results_loader.py", line 57, in generate_diffs
    return td.diff_results()
  File "/usr/lib/python3.6/site-packages/covscanhub/service/processing.py", line 123, in diff_results
    return self.generate_diff_files()
  File "/usr/lib/python3.6/site-packages/covscanhub/service/processing.py", line 100, in generate_diff_files
    add_title_to_json(self.paths.get_json_added(), 'Newly introduced defects')
  File "/usr/lib/python3.6/site-packages/covscanhub/service/processing.py", line 129, in add_title_to_json
    loaded_json = json.load(fd)
  File "/usr/lib64/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4308: ordinal not in range(128)
```