packaging: make sure that %{bash_completions_dir} is defined
... in the buildroot to avoid the following build failure:
```
[...]
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
mangling shebang in /usr/lib/python3.6/site-packages/osh/hub/manage.py from /usr/bin/env python3 to #!/usr/libexec/platform-python
mangling shebang in /usr/sbin/osh-stats from /usr/bin/env python3 to #!/usr/libexec/platform-python
mangling shebang in /usr/sbin/osh-worker from /usr/bin/env python3 to #!/usr/libexec/platform-python
Processing files: osh-client-0.9.3.git.20230519.144932.2677000-1.el8.noarch
error: File must begin with "/": %{bash_completions_dir}/osh-cli.bash
```