covscanhub: eliminate superfluous quoting in extract_tarball()
We should not shell-quote exec arguments when not invoking any shell.
Otherwise we get tracebacks like this for NVRs containing tilde:

Fault: <Fault 1: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/kobo/django/xmlrpc/dispatcher.py", line 95, in _marshaled_dispatch
    response = self._dispatch(method, params)
  File "/usr/lib64/python2.6/SimpleXMLRPCServer.py", line 418, in _dispatch
    return func(*params)
  File "/usr/lib/python2.6/site-packages/kobo/hub/decorators.py", line 19, in _new_func
    return func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/covscanhub/xmlrpc/worker.py", line 50, in finish_task
    td.unpack_results()
  File "/usr/lib/python2.6/site-packages/covscanhub/waiving/results_loader.py", line 49, in unpack_results
    rex.extract_tarball(self.exclude_dirs)
  File "/usr/lib/python2.6/site-packages/covscanhub/service/csmock_parser.py", line 107, in extract_tarball
    subprocess.check_call(command)
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['tar', '-xf', "'/var/lib/covscanhub/tasks/0/140000/142708/efivar-36-2~pj1.el8.tar.xz'", '-C', '/var/lib/covscanhub/tasks/0/140000/142708', '--wildcards', '--wildcards-match-slash', u'--exclude=*cov', '--exclude=*debug']' returned non-zero exit status 2
Frame check_call in /usr/lib64/python2.6/subprocess.py at line 505
<CODE>
     498     check_call(["ls", "-l"])
     499     """
     500     retcode = call(*popenargs, **kwargs)
     501     cmd = kwargs.get("args")
     502     if cmd is None:
     503         cmd = popenargs[0]
     504     if retcode:
-->  505         raise CalledProcessError(retcode, cmd)
     506     return retcode
     507
     508
     509 def list2cmdline(seq):
     510     """
     511     Translate a sequence of arguments into a command line
</CODE>
<LOCALS>
                 cmd = ['tar', '-xf', "'/var/lib/covscanhub/tasks/0/140000/142708/efivar-36-2~pj1.el8.tar.xz'", '-C', '/var/lib/covscanhub/tasks/0/140000/142708', '--wildcards', '--wildcards-match-slash', u'--exclude=*cov',
              kwargs = {}
           popenargs = ['tar', '-xf', "'/var/lib/covscanhub/tasks/0/140000/142708/efivar-36-2~pj1.el8.tar.xz'", '-C', '/var/lib/covscanhub/tasks/0/140000/142708', '--wildcards', '--wildcards-match-slash', u'--exclude=*cov',
             retcode = 2
</LOCALS>