containers: fix compose cleanup when --force is used
Fixes the following traceback:
```
+ podman-compose -p osh down a69f95600469 91ed93afa2b3 5e4b6337c75b
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.5.1
Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 2941, in main
    podman_compose.run()
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1423, in run
    cmd(self, args)
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 1754, in wrapped
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 2149, in compose_down
    excluded = get_excluded(compose, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/podman_compose.py", line 2020, in get_excluded
    excluded -= compose.services[service]["_deps"]
                ~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'a69f95600469'
```

Fixes: 4af45c74b02335ed0b15e7d4185b66a16210caed ("containers: scripts/deploy: simplify prepare_deploy")