covscanhub/waiving/results_loader.py: improve the last fix
... so that it does not fail on function names given as int:

Scan failed due to: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/covscanhub/scan/xmlrpc_helper.py", line 35, in finish_scan
    process_scan(sb)
  File "/usr/lib/python2.6/site-packages/covscanhub/waiving/results_loader.py", line 217, in process_scan
    rl.process()
  File "/usr/lib/python2.6/site-packages/covscanhub/waiving/results_loader.py", line 196, in process
    self.store_defects(self.all.get_defects(), DEFECT_STATES['NEW'])
  File "/usr/lib/python2.6/site-packages/covscanhub/waiving/results_loader.py", line 182, in store_defects
    d.function = d.function[:128]
TypeError: 'int' object is unsubscriptable