covscan: do not require django on the client
... unless we are self-testing Covscan.  This commit fixes a regression
introduced in 81b122cf3de7efcaf276bf766b16d10ed4d5478d:

    Traceback (most recent call last):
      File "/usr/bin/covscan", line 48, in <module>
        sys.exit(main())
      File "/usr/bin/covscan", line 26, in main
        CovScanCommandContainer.register_module(covscan.commands, prefix="cmd_")
      File "/usr/lib/python2.7/site-packages/kobo/plugins.py", line 171, in register_module
        __import__(module.__name__, {}, {}, module_list)
      File "/usr/lib/python2.7/site-packages/covscan/commands/cmd_diff_build.py", line 9, in <module>
        from covscan.commands.shortcuts import verify_brew_koji_build, verify_mock, \
      File "/usr/lib/python2.7/site-packages/covscan/commands/shortcuts.py", line 8, in <module>
        from django.conf import settings
    ImportError: No module named django.conf