hub: use correct method to mark task as failed
... in the XMLRPC API.

Fixes the following traceback:
```
Traceback (most recent call last):
  File "/src/kobo/kobo/worker/taskmanager.py", line 423, in run_task
    task.run()
  File "/src/osh/worker/tasks/task_get_analyzer_versions.py", line 53, in run
    self.hub.worker.finish_analyzers_version_retrieval(self.task_id, base_path)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/src/kobo/kobo/xmlrpc.py", line 629, in request
    result = transport_class.request(self, *args, **kwargs)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/src/kobo/kobo/xmlrpc.py", line 523, in _single_request3
    return self.parse_response(response)
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib64/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: Traceback (most recent call last):
  File "/src/kobo/kobo/django/xmlrpc/dispatcher.py", line 95, in _marshaled_dispatch
    response = self._dispatch(method, params)
  File "/usr/lib64/python3.6/xmlrpc/server.py", line 405, in _dispatch
    return func(*params)
  File "/src/kobo/kobo/hub/decorators.py", line 22, in _new_func
    return func(request, *args, **kwargs)
  File "/src/osh/hub/cs_xmlrpc/worker.py", line 84, in finish_analyzers_version_retrieval
    task.fail()
AttributeError: 'Task' object has no attribute 'fail'
```

Fixes: 2c09c711142ea53df87f6d48cadd85e81e320ea2 ("dont traceback when version retrieval fails")