hub: try to correctly guess the package name from file upload
Fixes the following traceback:
```
$ tar -czf systemd-1b717ce.tar.gz --files-from=/dev/null
$ osh-cli mock-build --tarball-build-script=: systemd-1b717ce.tar.gz
Traceback (most recent call last):
  File "/home/lukas/redhat/OpenScanHub/osh/client/osh-cli", line 77, in <module>
    main()
  File "/home/lukas/redhat/OpenScanHub/osh/client/osh-cli", line 70, in main
    parser.run()
  File "/home/lukas/redhat/OpenScanHub/kobo/kobo/cli.py", line 296, in run
    cmd.run(*cmd_args, **cmd_kwargs)
  File "/home/lukas/redhat/OpenScanHub/osh/client/commands/cmd_diff_build.py", line 167, in run
    task_id = self.submit_task(config, comment, options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/redhat/OpenScanHub/osh/client/commands/cmd_mock_build.py", line 23, in submit_task
    handle_perm_denied(e, self.parser)
  File "/home/lukas/redhat/OpenScanHub/osh/client/commands/cmd_mock_build.py", line 21, in submit_task
    return self.hub.scan.mock_build(config, comment, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/redhat/OpenScanHub/kobo/kobo/xmlrpc.py", line 629, in request
    result = transport_class.request(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukas/redhat/OpenScanHub/kobo/kobo/xmlrpc.py", line 523, in _single_request3
    return self.parse_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
           ^^^^^^^^^
  File "/usr/lib/python3.11/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: Traceback (most recent call last):
  File "/src/osh/hub/errata/check.py", line 23, in check_nvr
    return parse_nvr(nvr)
  File "/src/kobo/kobo/rpmlib.py", line 196, in parse_nvr
    raise ValueError("Invalid NVR: %s" % nvr)
ValueError: Invalid NVR: system
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/src/kobo/kobo/django/xmlrpc/dispatcher.py", line 95, in _marshaled_dispatch
    response = self._dispatch(method, params)
  File "/usr/lib64/python3.6/xmlrpc/server.py", line 405, in _dispatch
    return func(*params)
  File "/src/kobo/kobo/django/xmlrpc/decorators.py", line 63, in _new_func
    return func(request, *args, **kwargs)
  File "/src/osh/hub/osh_xmlrpc/scan.py", line 68, in mock_build
    return __client_build(request, options, ClientScanScheduler)
  File "/src/osh/hub/osh_xmlrpc/scan.py", line 37, in __client_build
    sched.prepare_args()
  File "/src/osh/hub/errata/scanner.py", line 416, in prepare_args
    self.priority, self.build_nvr, self.srpm_name)
  File "/src/osh/hub/errata/scanner.py", line 340, in determine_priority
    nvr_dict = check_nvr(supposed_nvr or srpm_name[:-8])
  File "/src/osh/hub/errata/check.py", line 26, in check_nvr
    raise RuntimeError('%s is not a correct N-V-R' % nvr)
RuntimeError: system is not a correct N-V-R
Frame check_nvr in /src/osh/hub/errata/check.py at line 26
<CODE>
      19
      20
      21 def check_nvr(nvr):
      22     try:
      23         return parse_nvr(nvr)
      24     except ValueError:
      25         logger.error('%s is not a correct N-V-R', nvr)
-->   26         raise RuntimeError('%s is not a correct N-V-R' % nvr)
      27
      28
      29 def check_package_is_blocked(package, release):
      30     is_blocked = package.is_blocked(release)
      31     if is_blocked:
      32         raise PackageBlockedException('Package %s is blocked.' %
</CODE>
<LOCALS>
                 nvr = 'system'
</LOCALS>
Frame determine_priority in /src/osh/hub/errata/scanner.py at line 340
<CODE>
     333         :rtype: int
     334         """
     335         if entered_priority is not None:
     336             return entered_priority
     337
     338         priority_offset = 0
     339         try:
-->  340             nvr_dict = check_nvr(supposed_nvr or srpm_name[:-8])
     341             packages = Package.objects.filter(name=nvr_dict['name'])
     342             if len(packages) == 1:
     343                 priority_offset = packages[0].get_priority_offset()
     344         except ValueError:
     345             pass
     346         return 10 + priority_offset
</CODE>
<LOCALS>
                 cls = <class 'osh.hub.errata.scanner.AbstractClientScanScheduler'>
    entered_priority = None
     priority_offset = 0
           srpm_name = 'systemd.tar.gz'
        supposed_nvr = None
</LOCALS>
Frame prepare_args in /src/osh/hub/errata/scanner.py at line 416
<CODE>
     409         """ prepare dicts -- arguments for task and scan """
     410         self.task_args['owner_name'] = self.username
     411         input_pkg = self.build_nvr or self.srpm_name
     412         self.task_args['label'] = input_pkg
     413         self.task_args['method'] = self.method
     414         self.task_args['comment'] = self.comment
     415         self.task_args['priority'] = AbstractClientScanScheduler.determine_priority(
-->  416             self.priority, self.build_nvr, self.srpm_name)
     417         self.task_args['state'] = TASK_STATES['CREATED']
     418         self.task_args['args'] = {}
     419         if self.build_nvr:
     420             self.task_args['args']['build'] = {
     421                 'nvr': self.build_nvr,
     422                 'koji_bin': self.build_kojibin,
</CODE>
<LOCALS>
           input_pkg = 'systemd.tar.gz'
                self = <osh.hub.errata.scanner.ClientScanScheduler object at 0x7fd718479f60>
self.additional_csmock_args = ''
self.analyzer_models = <ClientAnalyzerQuerySet []>
      self.analyzers = ''
      self.build_nvr = None
self.client_csmock_args = None
        self.comment = None
       self.email_to = None
     self.is_tarball = True
         self.method = 'MockBuild'
    self.mock_config = 'fedora-rawhide-x86_64'
     self.model_name = None
        self.options = {'comment': None, 'mock_config': 'fedora-rawhide-x86_64', 'upload_id': 3, 'tarball_build_script': ':', 'task_user': 'user', 'user': <SimpleLazyObject: <User: user>>}
       self.priority = None
        self.profile = 'default'
self.profile_analyzers = ['gcc', 'clang', 'cppcheck', 'shellcheck']
   self.profile_args = '--use-host-cppcheck --gcc-analyze'
      self.srpm_name = 'systemd.tar.gz'
      self.srpm_path = './osh/hub/upload/kyPnvzF7TIBrMHyGMiZsuLhHSDxovcYk/systemd.tar.gz'
      self.task_args = {'owner_name': 'user', 'label': 'systemd.tar.gz', 'method': 'MockBuild', 'comment': None}
      self.upload_id = 3
self.upload_model_id = None
           self.user = <SimpleLazyObject: <User: user>>
       self.username = 'user'
</LOCALS>
Frame __client_build in /src/osh/hub/osh_xmlrpc/scan.py at line 37
<CODE>
      30 def __client_build(request, options, Scheduler):
      31     """
      32     creates a user scan with given options and Scheduler
      33     """
      34     options['task_user'] = request.user.username
      35     options['user'] = request.user
      36     sched = Scheduler(options)
-->   37     sched.prepare_args()
      38     return sched.spawn()
      39
      40
      41 @login_required
      42 def diff_build(request, mock_config, comment, options, *args, **kwargs):
      43     """
</CODE>
```

Fixes: c6fd0d1023c350c842a904956769bbdd6e1dfd8b ("Add priority offset feature")
Resolves: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/234