hub: add missing leading '/' to 'scan/mock' url
Fixes the following test failure:
```
======================================================================
FAIL: test_mockconfs_list (osh.hub.waiving.tests.BasicWebTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/test/utils.py", line 373, in inner
    return func(*args, **kwargs)
  File "/src/osh/hub/waiving/tests.py", line 59, in test_mockconfs_list
    self.assertEqual(r.status_code, 200)
AssertionError: 404 != 200
```

Fixes: e027357d8a2c83add2393044f4f068486d152127