cmd_list_analyzers.py: add missing backslashes
... to fix the following backtrace:

Traceback (most recent call last):
  File "/usr/bin/covscan", line 48, in <module>
    sys.exit(main())
  File "/usr/bin/covscan", line 40, in main
    parser.run(args)
  File "/usr/lib/python2.7/site-packages/kobo/cli.py", line 271, in run
    cmd, cmd_opts, cmd_args = self.parse_args(args, values)
  File "/usr/lib/python2.7/site-packages/kobo/cli.py", line 265, in parse_args
    cmd.options()
  File "/usr/lib/python2.7/site-packages/covscan/commands/cmd_list_analyzers.py", line 19, in options
    + " list contains command line arguments how to enable particular analyzer (short version,"
TypeError: bad operand type for unary +: 'str'