covscan.spec: require python2-requests for covscan-client
... to avoid the following tracaback on f31:

Traceback (most recent call last):
  File "/usr/bin/covscan", line 48, in <module>
    sys.exit(main())
  File "/usr/bin/covscan", line 26, in main
    CovScanCommandContainer.register_module(covscan.commands, prefix="cmd_")
  File "/usr/lib/python2.7/site-packages/kobo/plugins.py", line 173, in register_module
    __import__(module.__name__, {}, {}, module_list)
  File "/usr/lib/python2.7/site-packages/covscan/commands/cmd_diff_build.py", line 9, in <module>
    from covscan.commands.shortcuts import verify_brew_koji_build, verify_mock, \
  File "/usr/lib/python2.7/site-packages/covscan/commands/shortcuts.py", line 3, in <module>
    import koji
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 53, in <module>
    import requests
ImportError: No module named requests