containers/scripts: fix issues reported by ShellCheck
```
Error: SHELLCHECK_WARNING:
containers/scripts/generate_integration_test_coverage.sh:100:17: style[SC2006]: Use $(...) notation instead of legacy backticks `...`.

Error: SHELLCHECK_WARNING:
containers/scripts/generate_integration_test_coverage.sh:103:21: style[SC2006]: Use $(...) notation instead of legacy backticks `...`.

Error: SHELLCHECK_WARNING:
containers/scripts/generate_integration_test_coverage.sh:119:17: style[SC2006]: Use $(...) notation instead of legacy backticks `...`.

Error: SHELLCHECK_WARNING:
containers/scripts/generate_integration_test_coverage.sh:122:21: style[SC2006]: Use $(...) notation instead of legacy backticks `...`.

Error: SHELLCHECK_WARNING:
containers/scripts/generate_integration_test_coverage.sh:131:10: warning[SC2046]: Quote this to prevent word splitting.
```

Related: https://github.com/openscanhub/openscanhub/issues/151
Closes: https://github.com/openscanhub/openscanhub/pull/312