covscanhub/waiving/results_loader.py: truncate function name
... to fit into the corresponding db field.  Otherwise we would
end up with the following traceback while finishing a task:

Scan failed due to: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/covscanhub/scan/xmlrpc_helper.py", line 35, in finish_scan
    process_scan(sb)
  File "/usr/lib/python2.6/site-packages/covscanhub/waiving/results_loader.py", line 212, in process_scan
    rl.process()
  File "/usr/lib/python2.6/site-packages/covscanhub/waiving/results_loader.py", line 194, in process
    self.store_defects(self.added.get_defects(), DEFECT_STATES['NEW'])
  File "/usr/lib/python2.6/site-packages/covscanhub/waiving/results_loader.py", line 184, in store_defects
    d.save()
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/usr/lib/python2.6/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.6/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.6/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.6/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(128)