Revert "Makefile: use python2 to make it work on f31"
This reverts commit 4033c5493ade2768809ab538c6bd7495b26e2105 because
it did not work well when python2-kobo* packages were not installed:

Traceback (most recent call last):
  File "setup.py", line 83, in <module>
    package_module = __import__(project_dirs[0] + ".version")
  File "/home/kdudka/git/covscan/covscan/__init__.py", line 6, in <module>
    import kobo.client.commands
ImportError: No module named kobo.client.commands
make: *** [Makefile:17: clean] Error 1