tests: update SCANS_CHANGELIST_ITEMS_PER_PAGE
... which is hard-coded in the test.  Its mismatch with the actual
implementation resulted in the following cryptic test failure:
```
FAIL: test_changelist_is_rendered_properly (osh.hub.scan.test_admin.ScanAdminTestSuite)
Test whether change list page has all expected elements.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/src/osh/hub/scan/test_admin.py", line 227, in test_changelist_is_rendered_properly
    self.verify_changelist_select_action(
  File "/src/osh/testing/testcases.py", line 267, in verify_changelist_select_action
    self.assertInParsedHTML(
  File "/src/osh/testing/testcases.py", line 52, in assertInParsedHTML
    self.assertGreater(element.count(parsed), 0)
AssertionError: 0 not greater than 0
```